Ext.define('PWApp2.store.StateStore', {
    extend: 'Ext.data.Store',
    storeId: 'StateStore',

    fields: [ 'name' ],
    data: [
        {name: 'ALABAMA' },
        {name: 'ALASKA' },
        {name: 'ARIZONA' },
        {name: 'ARKANSAS' },
        {name: 'CALIFORNIA' },
        {name: 'COLORADO' },
        {name: 'FLORIDA' },
        {name: 'GEORGIA' },
        {name: 'IDAHO' },
        {name: 'ILLINOIS' },
        {name: 'INDIANA' },
        {name: 'KANSAS' },
        {name: 'KENTUCKY' },
        {name: 'LOUISIANA' },
        {name: 'MARYLAND' },
        {name: 'MICHIGAN' },
        {name: 'MISSISSIPPI' },
        {name: 'MISSOURI' },
        {name: 'MONTANA' },
        {name: 'NEBRASKA' },
        {name: 'NEVADA' },
        {name: 'NEW MEXICO' },
        {name: 'NEW YORK' },
        {name: 'NORTH DAKOTA' },
        {name: 'OHIO' },
        {name: 'OKLAHOMA' },
        {name: 'OREGON' },
        {name: 'PENNSYLVANIA' },
        {name: 'SOUTH DAKOTA' },
        {name: 'TEXAS' },
        {name: 'UTAH' },
        {name: 'WASHINGTON' },
        {name: 'WEST VIRGINIA' },
        {name: 'WYOMING' }
    ]    
});
